Dropout:
- args:
  - f8
  - false
  - true
  state:
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  GL/NWFKh1T8=
Epochs: 50
Hidden: 256
Hybrid_Model: PSO + CSA Optimized LSTM
